// Using only Cabin font throughout the design system
// Google Fonts commented out - Cabin loaded via CSS
import "/public/assets/css/bootstrap.css"
import "/public/assets/css/widgets.css"
import "/public/assets/css/color-default.css"
import "/public/assets/css/fontello.css"
import "/public/assets/css/style.css"
import "/public/assets/css/responsive.css"
import "./globals.css"
import type { Metadata } from "next"

// const cabin = Cabin({
// 	subsets: ['latin'],
// 	display: 'swap',
// })

// const b612Mono = B612_Mono({
// 	subsets: ['latin'],
// 	display: 'swap',
// 	weight: ['400', '700'],
// 	variable: '--font-b612-mono',
// })

export const metadata: Metadata = {
	title: "Merinda - Multi-purpose Bootstrap 5 Next.js Template",
	description: "Generated by Merinda - Multi-purpose Bootstrap 5 Next.js Template"
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="home" suppressHydrationWarning>{children}</body>
		</html>
	)
}
